### PR TITLE
Angular 10 support

### PR DESCRIPTION
**Pull request by KingDarBoja**
**Work in Progress!**

### CODE REVIEW

**Comment by pasevin** [comment]
@KingDarBoja any updates on this? Should we still have hope? Or start looking for alternatives?

**Comment by mino922** [comment]
Any updates on this? @KingDarBoja

**Comment by KingDarBoja** [comment]
Sorry for the late response, been busy with work and other libraries at the time being. I am going to be honest, I don't have the motivation neither the help to keep supporting this package so probably gonna step back and close this PR.

I would either recommend other alternatives like [nx-plugins](https://github.com/flowaccount/nx-plugins), which I haven't tested fully on deploy for AWS (I don't have an account) or recommend learning how to setup Universal + Serverless, which should be a good experience for any developer :)

**Comment by pasevin** [comment]
Hey, @KingDarBoja thanks for the effort! I understand the struggle.  It was nice while it lasted.
I will check out the nx-plugins, but probably as you said, will go with a pure approach instead.
If you have any good links from your experience about this topic, please share.

**Comment by KingDarBoja** [comment]
Sure, I think the main issue with this setup is trying to do multiple stuff with old approaches as Angular has a faster release cycle (6 months per major version) and there aren't many people trying out serverless + universal with either AWS, Firebase (GCP) and so on. This is reflected in the ammount of countributions of this package and also for the linked nx-plugin repository, so maybe this is a known issue and best effort should be trying to contribute by solving some open issues on the most up-to-date package.

**Pull request closed without merging**
