### PR TITLE
[Bugfix] Fix ng-toolkit errors

### PR DESCRIPTION
**Pull request by KingDarBoja**
@maciejtreder This PR does fix `init` and `serverless` test files along with an Angular upgrade to the latest version (8.3.3).

**UPDATE**
- Updates dependencies for each schematic.
- Moved any function that makes uses of typescript definition to utils schematic folder.
- Updates test suite for each schematic.
- Add missing schema files.
- Code refactoring to easily comment out any rule on a chain.
- Fix default serverless node version to 10.x
- All schematic version were changed to **8.0.0** in order to refer to the latest Angular supported version.

### CODE REVIEW

**Comment by maciejtreder** [comment]
Hello @KingDarBoja !

Thanks for this PR, I will review it ASAP (I think that I will find some time till the end of this week).

**Comment by KingDarBoja** [comment]
@maciejtreder Success! 🍰 

Log after running locally the schematic with relative path (`schematics ../ng-toolkit/schematics/init/src/collection.json:ng-new mysupertest --debug=false`):

```sh-session
CREATE /mysupertest/angular.json (5845 bytes)
CREATE /mysupertest/package.json (3897 bytes)
CREATE /mysupertest/README.md (5222 bytes)
CREATE /mysupertest/tsconfig.json (544 bytes)
CREATE /mysupertest/tslint.json (1566 bytes)
CREATE /mysupertest/.editorconfig (246 bytes)
CREATE /mysupertest/.gitignore (374 bytes)
CREATE /mysupertest/browserslist (429 bytes)
CREATE /mysupertest/karma.conf.js (1023 bytes)
CREATE /mysupertest/tsconfig.app.json (270 bytes)
CREATE /mysupertest/tsconfig.spec.json (270 bytes)
CREATE /mysupertest/src/favicon.ico (5430 bytes)
CREATE /mysupertest/src/index.html (5575 bytes)
CREATE /mysupertest/src/polyfills.ts (3186 bytes)
CREATE /mysupertest/src/styles.css (81 bytes)
CREATE /mysupertest/src/test.ts (685 bytes)
CREATE /mysupertest/src/assets/.gitkeep (0 bytes)
CREATE /mysupertest/src/environments/environment.prod.ts (51 bytes)
CREATE /mysupertest/src/environments/environment.ts (662 bytes)
CREATE /mysupertest/src/app/app.module.ts (3326 bytes)
CREATE /mysupertest/src/app/app.component.html (472 bytes)
CREATE /mysupertest/src/app/app.component.spec.ts (4898 bytes)
CREATE /mysupertest/src/app/app.component.ts (2814 bytes)
CREATE /mysupertest/src/app/app.component.css (0 bytes)
CREATE /mysupertest/e2e/protractor.conf.js (810 bytes)
CREATE /mysupertest/e2e/tsconfig.json (214 bytes)
CREATE /mysupertest/e2e/src/app.e2e-spec.ts (644 bytes)
CREATE /mysupertest/e2e/src/app.po.ts (262 bytes)
CREATE /mysupertest/credentials.js (383 bytes)
CREATE /mysupertest/LICENSE (1091 bytes)
CREATE /mysupertest/local.js (244 bytes)
CREATE /mysupertest/ngsw-config.json (822 bytes)
CREATE /mysupertest/src/main.server.ts (227 bytes)
CREATE /mysupertest/src/manifest.json (1249 bytes)
CREATE /mysupertest/src/tsconfig.app.json (324 bytes)
CREATE /mysupertest/src/tsconfig.server.json (421 bytes)
CREATE /mysupertest/src/tsconfig.spec.json (302 bytes)
CREATE /mysupertest/src/app/app.browser.module.ts (1203 bytes)
CREATE /mysupertest/src/app/app.component.scss (563 bytes)
CREATE /mysupertest/src/app/app.server.module.ts (1543 bytes)
CREATE /mysupertest/src/app/window-ref.service.ts (786 bytes)
CREATE /mysupertest/src/app/donors/donors.component.html (1820 bytes)
CREATE /mysupertest/src/app/donors/donors.component.ts (297 bytes)
CREATE /mysupertest/src/app/home/home.component.html (2761 bytes)
CREATE /mysupertest/src/app/home/home.component.spec.ts (646 bytes)
CREATE /mysupertest/src/app/home/home.component.ts (219 bytes)
CREATE /mysupertest/src/app/lazy/lazy.component.html (407 bytes)
CREATE /mysupertest/src/app/lazy/lazy.component.spec.ts (662 bytes)
CREATE /mysupertest/src/app/lazy/lazy.component.ts (165 bytes)
CREATE /mysupertest/src/app/lazy/lazy.module.ts (344 bytes)
CREATE /mysupertest/src/app/menu/menu.component.html (1773 bytes)
CREATE /mysupertest/src/app/menu/menu.component.scss (1147 bytes)
CREATE /mysupertest/src/app/menu/menu.component.spec.ts (4733 bytes)
CREATE /mysupertest/src/app/menu/menu.component.ts (2227 bytes)
CREATE /mysupertest/src/app/services/exampleApi.service.ts (440 bytes)
CREATE /mysupertest/src/app/services/notifications.service.spec.ts (7952 bytes)
CREATE /mysupertest/src/app/services/notifications.service.ts (4848 bytes)
CREATE /mysupertest/src/app/services/service-worker.mock.module.ts (442 bytes)
CREATE /mysupertest/src/app/services/snack-bar.service.spec.ts (4081 bytes)
CREATE /mysupertest/src/app/services/snack-bar.service.ts (2366 bytes)
CREATE /mysupertest/src/app/services/swPush-server.mock.service.ts (456 bytes)
CREATE /mysupertest/src/app/services/swUpdate-server.mock.service.ts (564 bytes)
CREATE /mysupertest/src/app/services/resolvers/hitWithoutTransferState.resolver.ts (498 bytes)
CREATE /mysupertest/src/app/services/resolvers/hitWithTransferState.resolver.ts (1281 bytes)
CREATE /mysupertest/src/app/transfer-state/transfer-state.component.css (1154 bytes)
CREATE /mysupertest/src/app/transfer-state/transfer-state.component.html (2588 bytes)
CREATE /mysupertest/src/app/transfer-state/transfer-state.component.ts (392 bytes)
CREATE /mysupertest/src/app/transfer-state/with-transfer-state.component.ts (573 bytes)
CREATE /mysupertest/src/app/transfer-state/without-transfer-state.component.ts (576 bytes)
CREATE /mysupertest/src/assets/browserconfig.xml (268 bytes)
CREATE /mysupertest/src/assets/i18n/de.json (37 bytes)
CREATE /mysupertest/src/assets/i18n/en.json (34 bytes)
CREATE /mysupertest/src/assets/i18n/es.json (36 bytes)
CREATE /mysupertest/src/assets/i18n/fr.json (36 bytes)
CREATE /mysupertest/src/assets/i18n/hi.json (62 bytes)
CREATE /mysupertest/src/assets/i18n/it.json (35 bytes)
CREATE /mysupertest/src/assets/i18n/nl.json (34 bytes)
CREATE /mysupertest/src/assets/i18n/pl.json (29 bytes)
CREATE /mysupertest/src/assets/i18n/ru.json (58 bytes)
CREATE /mysupertest/src/assets/i18n/sk.json (33 bytes)
CREATE /mysupertest/src/assets/i18n/tr.json (36 bytes)
CREATE /mysupertest/src/assets/icons/favicon-144.png (4335 bytes)
CREATE /mysupertest/src/assets/icons/favicon-192.png (6502 bytes)
CREATE /mysupertest/src/assets/icons/favicon-32.png (573 bytes)
CREATE /mysupertest/src/assets/icons/favicon-48.png (950 bytes)
CREATE /mysupertest/src/assets/icons/favicon-512.png (28650 bytes)
CREATE /mysupertest/src/assets/icons/favicon-72.png (1684 bytes)
CREATE /mysupertest/src/assets/icons/favicon-96.png (2544 bytes)
CREATE /mysupertest/src/assets/icons/favicon.ico (152126 bytes)
CREATE /mysupertest/src/assets/icons/favicon.png (6502 bytes)
CREATE /mysupertest/src/assets/icons/mstile-150x150.png (4692 bytes)
CREATE /mysupertest/src/assets/icons/safari-pinned-tab.svg (35736 bytes)
CREATE /mysupertest/src/assets/img/background.png (72398 bytes)
CREATE /mysupertest/src/assets/img/lighthouse_report.png (28918 bytes)
CREATE /mysupertest/src/styles/credentials.scss (432 bytes)
CREATE /mysupertest/src/styles/main.scss (823 bytes)
CREATE /mysupertest/src/main.browser.ts (452 bytes)
CREATE /mysupertest/ng-toolkit.json (243 bytes)
CREATE /mysupertest/webpack.server.config.js (1132 bytes)
CREATE /mysupertesttemp/server_universal.ts15 (1296 bytes)
CREATE /mysupertest/server.ts (553 bytes)
CREATE /mysupertest/lambda.js (888 bytes)
CREATE /mysupertest/serverless.yml (735 bytes)
```

And the folder was created without erros 💯

**Comment by pasevin** [comment]
@KingDarBoja thanks for this! Is there an instruction somewhere how to properly build this and use in my project right now?

**Comment by KingDarBoja** [comment]
> @KingDarBoja thanks for this! Is there an instruction somewhere how to properly build this and use in my project right now?

Yes, I do recommend reading this [article](https://medium.com/@tomastrajan/total-guide-to-custom-angular-schematics-5c50cf90cdb4) in order to get insight of how to run it.

The thing is that you need to create symbolic links between the packages because each one depends on others. All of them rely on the same `@ng-toolkit/_utils` package so that's the first one you must run  a build and then use `npm link` in order to generate the link.

Then just move to each other package and run `npm link @ng-toolkit/_utils` to link the previous package to the current one. Same thing applies for `serverless`, `universal`, `firebug` and `pwa` depending on which schematic you wanna run.

The good thing about using symbolic links is that any changes you do on the linked schematic, it propagates to the packages were it is being used.

Once everything is connected and built, excute the schematic by using the next command:
`schematics /relative/path/to/schematics/schematicName/collection.json:commandName projectName`. 

As example, I do want to execute the `ng-toolkit/init` package to generate the boilerplate app with *mysuperawesometest* as project name, I would have to type `schematics ../ng-toolkit/schematics/init/src/collection.json:ng-new mysuperawesometest --debug=false`.

The debug flag is for generate the app files because using relative paths to the schematic json will not generate files by default.

Cheers!

**Comment by pasevin** [comment]
Thanks! Will do. 

> The thing is that you need to create symbolic links between the packages because each one depends on others. 

This was driving me crazy!

**Comment by KingDarBoja** [comment]
> Thanks! Will do.
> 
> > The thing is that you need to create symbolic links between the packages because each one depends on others.
> 
> This was driving me crazy!

Did everything work as expected for you? I do find minor fixes to be done with Angular 8, like as:
- **Fix lazy loading regex on `prerender` file.** This is due to Angular 8 new syntax for lazy loaded modules.
- **Fix appending code block for ngOnInit on serverless `index.ts` file.**
- **Add typing definitions and rename shadowed variables inside `prerender` file (Optional).**
- **Set minimal version for some packages like as nguniversal instea of `0.0.0`.**

Cheers!

**Comment by maciejtreder** [comment]
Finally merged!

@KingDarBoja Big, big thanks for your input. The deploy is coming.

Would you like me to add you as a collaborator to this project?

**Comment by KingDarBoja** [comment]
> Finally merged!
> 
> @KingDarBoja Big, big thanks for your input. The deploy is coming.
> 
> Would you like me to add you as a collaborator to this project?

No problem mate, glad to help with this, been pretty awesome to find these kind of projects around here, really saves the time for most of us.

And yeah, go ahead :)

**Pull request merged**
